### PR TITLE
feat: new look and feel

### PR DESCRIPTION
**Pull request by jpradocueva**
This PR contains changes to the website style.
See Issue #26

### CODE REVIEW

**Comment by JTrakinat** [comment]
If this changes the column headings to blue, it is fine by me (I could see the coding, but couldn't get it to actually show the changed page)
R/JCT

Jean C. Trakinat
Principal Engineer, Systems Architecture

***@***.***
+1-719-271-0309
***@***.***

**Comment by jpradocueva** [comment]
@JTrakinat  this image summarizes the later changes.

## New Look & Feel
image

**Comment by JTrakinat** [comment]
I like this (color format) better.   Small nits -- delete "coming" from event column header (the "next" or future event may be "coming" but the previous events are listed).

**Comment by JTrakinat** [comment]
I'd go ahead and merge this as this seems (IMHO) better than what is currently there.  If Matt/Hannes want it changed, we can do that later.

Cheers,
JCT

Jean C. Trakinat
Principal Engineer, Systems Architecture

***@***.***
+1-719-271-0309
***@***.***

**Pull request merged**
